### ISSUE TITLE
Support for Arduino SAMD boards?

### ISSUE THREAD

**Issue by cwittwer** [Infineon/arduino-pas-co2-sensor#15]
Just curious if there will be or is support for Arduino SAMD boards(in my case using a MKR WiFi 1010)?

**Comment by jaenrig-ifx** [comment]
Dear @cwittwer, 

In principle other Arduino core should also work with the library. But that in practice that is not the case. I just see that the inconsistencies with the attachInterrupt() function signature arg types are making the build fail. 
We will spend some time on this issue after Xmas holiday.

Thanks for your patience :)
