### ISSUE TITLE
serial-alarm.ino example shows co2 ppm value as 0 (with error code 7) when sensor is connected to Arduino UNO

### ISSUE THREAD

**Issue by Anandaramashetty** [Infineon/arduino-pas-co2-sensor#3]
**Prerequisites**

Can you reproduce the problem reliably?
Yes

**Description**:
Hi ,

I am trying to use the example serial-alarm from arduino-pas-co2-sensor-master library(version 2.0.0). But in serial terminal, getting error code 1 and 7. Attached is the snapshots for your reference. Can you please check and let me know.

**Steps to Reproduce:**

1. Arduino uno board is connected PAS-CO2 sensor.
2. 12 volt and 3.3 v for the sensor is taken from sensor2go kit.
3. Open the code example serial-alarm.ino available in  Arduino\libraries\arduino-pas-co2-sensor-master\examples\serial-alarm.
4. Modified I2C_FREQ_HZ value 100000 and interrupt_pin to 3 in serial-alarm.ino
5. Changed the PASCO2_INO_INT macro value to 3 from 0xFF  in pas-co2-platf-ino.hpp since we are using Pin #3 for interrupt.
6. In pas-co2-serial-ino.hpp file and in startMeasure function, the value of alarmTh is modified to 24000 from 0
7. Run the code example serial-alarm.ino

**Expected Result:**

A non zero co2 ppm value.

**Actual Result:**

![2](https://user-images.githubusercontent.com/99385405/155714125-dc1f9472-7040-49ec-9a51-f5ebf55bb61a.JPG)

**Frequency (1/1, 1/50, 1/100):**
100

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.
2.0.0

**Target:**

Arduino uno board 

**Host OS and Version:**

Windows 64 bit

**Environment**
Arduino ide

**Comment by jaenrig-ifx** [comment]
Hi @Anandaramashetty, 

The new release https://github.com/Infineon/arduino-pas-co2-sensor/releases/tag/v2.1.0 might solve partially the measuring mismatch issues.
